### ISSUE TITLE
mac err:  npm run dev 

### ISSUE THREAD

**Issue by redpeer** [xufqing/rest_xops#20]
>  cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack-dev-server ENOENT
    at _errnoException (util.js:1003:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xops-qt@1.2.0 dev: ` cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xops-qt@1.2.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by redpeer** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@5.7.1
3 info using node@v9.4.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle xops-qt@1.2.0~predev: xops-qt@1.2.0
6 info lifecycle xops-qt@1.2.0~dev: xops-qt@1.2.0
7 verbose lifecycle xops-qt@1.2.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle xops-qt@1.2.0~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/thz-mac/PythonWork/rest_xops/xops_qd/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/Caskroom/android-sdk/3859397/tools:/usr/local/Caskroom/android-sdk/3859397/platform-tools:/usr/local/Caskroom/android-sdk/3859397/tools:/usr/local/Caskroom/android-sdk/3859397/tools:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/bin:/Users/thz-mac/Documents/maven/bin
9 verbose lifecycle xops-qt@1.2.0~dev: CWD: /Users/thz-mac/PythonWork/rest_xops/xops_qd
10 silly lifecycle xops-qt@1.2.0~dev: Args: [ '-c',
10 silly lifecycle   ' cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js' ]
11 silly lifecycle xops-qt@1.2.0~dev: Returned: code: 1  signal: null
12 info lifecycle xops-qt@1.2.0~dev: Failed to exec dev script
13 verbose stack Error: xops-qt@1.2.0 dev: ` cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid xops-qt@1.2.0
15 verbose cwd /Users/thz-mac/PythonWork/rest_xops/xops_qd
16 verbose Darwin 17.6.0
17 verbose argv "/usr/local/Cellar/node/9.4.0/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v9.4.0
19 verbose npm  v5.7.1
20 error code ELIFECYCLE
21 error errno 1
22 error xops-qt@1.2.0 dev: ` cross-env BABEL_ENV=development webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
22 error Exit status 1

**Comment by Yangsiyu0117** [comment]
I had the same problem as you.Excuse me, did you solve it?
